fix: patch random.c
```
  src/random.c:13:8: error: address argument to atomic operation must be a pointer to _Atomic type ('int *' invalid)
                  if (!atomic_compare_exchange_strong(&fd, &expect, tmp))
                       ^                              ~~~
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/stdatomic.h:139:67: note: expanded from macro 'atomic_compare_exchange_strong'
  #define atomic_compare_exchange_strong(object, expected, desired) __c11_atomic_compare_exchange_strong(object, expected, desired, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)
                                                                    ^                                    ~~~~~~
  1 error generated.
```

Signed-off-by: Rui Chen <rui@chenrui.dev>